### ISSUE TITLE
CommPath object from Seurat

### ISSUE THREAD

**Issue by Flyingcattle** [yingyonghui/CommPath#1]
Hi, Yonghui,
Thank you for providing such a useful tool. I'd like to try using CommPath to analyze my data. Currently, I have a Seurat object. Could you please share how to extract the necessary files from the Seurat object to build a CommPath object? Your assistance is greatly appreciated.

**Comment by yingyonghui** [comment]
Hi @Flyingcattle ,
I'm glad this tool has been helpful to you. To create the CommPath object, the expression matrix (in matrix format) and cell identity information (in vector or dataframe format) are required.
Specifically, for Seurat V2, the following code would be helpful:
```
expr.mat <- seurat@data
cell.info <- seurat@meta.data$Cluster
obj <- createCommPath(expr.mat = expr.mat, cell.info = cell.info, species = "hsapiens")
```

For Seurat V3 or the later version, the following code would be helpful:
```
expr.mat <- seurat@assays$RNA@data
cell.info <- seurat@meta.data$Cluster
obj <- createCommPath(expr.mat = expr.mat, cell.info = cell.info, species = "hsapiens")
```
Best wishes!
Yonghui
