### ISSUE TITLE
About the difficulties I encountered in modifying the colors of circosPlot

### ISSUE THREAD

**Issue by Liuzhr9** [yingyonghui/CommPath#2]
At your convenience, would you please help me solve the bug. When I use circosPlot {CommPath}, I want to change the color. I looked at the help file and called ident.col as follows:
identcol <-  c("#BC8F8F","#FFC1C1","#20B2AA","#2C4F99","#FFA500","#EFBA60","#20B2AA","#8B008B")
names(identcol) <- c("Ependymal_cells","Vascular_cells","Neurons","AC","Oligo","OPC","Microglia","PBM")
circosPlot(object = PBS.obj, plot="count", filter=FALSE,select.ident = "PBM",ident.col =identcol )

Error in circosPlot(object = PBS.obj, plot = "count", filter = FALSE,  : 
  The color of  may be missed in the input color

大佬救命！！！！！！！ 求求

**Comment by yingyonghui** [comment]
Hi @Liuzhr9 ,
I am pleased to hear that CommPath has proven beneficial for your work. Thank you for bringing the bug to our attention. I have thoroughly debugged the software and subsequently updated the package. I encourage you to download the latest version and give it another attempt. I am hopeful that this will effectively resolve the issue you encountered. Please do not hesitate to reach out if you have any questions or require further assistance.

Best
Yonghui
