### ISSUE TITLE
Failure in intensity circosPlot

### ISSUE THREAD

**Issue by crebli** [yingyonghui/CommPath#5]
hi,
**circosPlot(object = comm, plot="intensity", filter=TRUE).**
Error in rep(small.gap, n_df1 - 1) : invalid 'times' argument.

We encountered such error many times which were almost in halves of our disposed data. How could we do that? However, it didn't happen in count circosPlot (circosPlot(object = comm, plot="count", filter=TRUE)).
Thank you!

**Comment by yingyonghui** [comment]
Hi @crebli 
Is the error occurring when using circosPlot with "filter=FALSE"? If no error occurs with "filter=FALSE", it is possible that there are very few ligand-receptor pairs when filtered with pathways. Can you please verify the variable "comm@interact.filter$InteractNumber"?

Best

**Comment by crebli** [comment]
> Hi @crebli Is the error occurring when using circosPlot with "filter=FALSE"? If no error occurs with "filter=FALSE", it is possible that there are very few ligand-receptor pairs when filtered with pathways. Can you please verify the variable "[comm@interact.filter](mailto:comm@interact.filter)$InteractNumber"?
> 
> Best

**Comment by crebli** [comment]
Hi，
The error occurred  either with "filter=TRUE" or with  "filter=FALSE". There are many ligand-receptor pairs when filtered.  But there also have some Inf in the value of intensity in [comm@interact.filter](mailto:comm@interact.filter)$InteractNumber. 

![image](https://github.com/yingyonghui/CommPath/assets/63771650/749f9c63-a683-47cc-af03-efdf31e2b666)
 
Thanks!
