### ISSUE TITLE
Hi，

### ISSUE THREAD

**Issue by crebli** [yingyonghui/CommPath#6]
Hi，
The error occurred  either with "filter=TRUE" or with  "filter=FALSE". There are many ligand-receptor pairs when filtered.  But there also have some Inf in the value of intensity in [comm@interact.filter](mailto:comm@interact.filter)$InteractNumber. 

![image](https://github.com/yingyonghui/CommPath/assets/63771650/749f9c63-a683-47cc-af03-efdf31e2b666)
 
Thanks!

_Originally posted by @crebli in https://github.com/yingyonghui/CommPath/issues/5#issuecomment-1879953579_

**Comment by yingyonghui** [comment]
My apologies for the late reply. I suspect there may be an issue with the expression matrix. Could you please check the contents of the variable "comm@LR.marker"? If it's convenient, could you provide an example dataset that I can use to reproduce the error and assist in debugging the package?

Best

**Comment by crebli** [comment]
hello，
 I have attached the data via email to you (E2.data.rds and the cell.info: E2.meta). please check it.
comm.data<-E2.data
comm <- createCommPath(expr.mat = comm.data, cell.info = E2.meta$celltype, species = "mouse")
Thank you!


Yinchuan
















At 2024-01-17 15:19:21, "yonghuiying" ***@***.***> wrote:

My apologies for the late reply. I suspect there may be an issue with the expression matrix. Could you please check the contents of the variable ***@***.***"? If it's convenient, could you provide an example dataset that I can use to reproduce the error and assist in debugging the package?

Best

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
E2.data.rds (45.82M, 2024年2月1日 16:50 到期)
下载
E2.meta.csv (266.51K, 2024年2月1日 16:50 到期)
下载

**Comment by yingyonghui** [comment]
Hi @crebli 
It seems there might be an issue with the website, and unfortunately, I am unable to download the attached file from GitHub. Could you please send the example dataset to my email at luh678@163.com? Thank you.

**Comment by yingyonghui** [comment]
Hi @crebli 
I've reviewed the expression matrix and noticed that it contains raw count data. For constructing the CommPath object, it's essential to first normalize the expression values by the library size and apply log transformation. The following code snippet can be helpful:

```
comm.data <- E2.data
comm.norm.data <-log(t(t(comm.data)*10000/colSums(comm.data) + 1))  # This line performs normalization similar to Seurat's NormalizeData function
comm <- createCommPath(expr.mat = comm.norm.data, cell.info = E2.meta$celltype, species = "mouse")
```

I'll incorporate the normalization function into CommPath and release an updated version later.

Best

**Comment by crebli** [comment]
Great job!
Thank you!
















At 2024-01-18 15:02:29, "yonghuiying" ***@***.***> wrote:

Hi @crebli
I've reviewed the expression matrix and noticed that it contains raw count data. For constructing the CommPath object, it's essential to first normalize the expression values by the library size and apply log transformation. The following code snippet can be helpful:

comm.data <- E2.data
comm.norm.data <-log(t(t(comm.data)*10000/colSums(comm.data) + 1))  # This line performs normalization similar to Seurat's NormalizeData function
comm <- createCommPath(expr.mat = comm.norm.data, cell.info = E2.meta$celltype, species = "mouse")


I'll incorporate the normalization function into CommPath and release an updated version later.

Best
