### ISSUE TITLE
Pathplot

### ISSUE THREAD

**Issue by NarainritKaruna** [yingyonghui/CommPath#8]
Hi,

Do you have any ideas on results of Pathplot function showing below:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/a31398ae-ad5a-4d81-ad39-f9e804478b1d">

there is no line between them, which is different from the example in your GitHub.

Best,

**Comment by yingyonghui** [comment]
Hi @NarainritKaruna 
Are you working fine on the sample data in the tutorial?

**Comment by NarainritKaruna** [comment]
Hi @yingyonghui 

it is my data, but I follow the tutorial, and I have no problems until pathplot() results.

**Comment by yingyonghui** [comment]
I've reviewed the sample data in the tutorial, and it just ran as expected. Could you provide an example dataset specific to your case so that I can replicate the error?

**Comment by yingyonghui** [comment]
Hi @NarainritKaruna 
I've reviewed your data. The reason there is no line between the points might be that the point sizes are so large that they cover the lines. Selecting a smaller value for dot.gene.size could help resolve the problem:

```
pathPlot(object, select.ident='SMC_3', acti.path.dat=acti.path.filtered, dot.gene.size=0.1)
```

In this graph, the size of the points represents only the relative value of the expression, not the absolute value.

**Comment by NarainritKaruna** [comment]
That works 
Thanks!
